contact_links:
  - name: General support and product feedback
    url: https://support.detahardrd.io
    about: Please do not use this Github repository for technical support. Contact detahardrd support directly or visit our community forum at forudetahardhard.io.
