APPVER = 1.0.0

NAME  = demo

OBJS += demo.o
OBJS += startup.o

OBJS += ../vendor/detahard-crypto/bignum.o
OBJS += ../vendor/detahard-crypto/bip32.o
OBJS += ../vendor/detahard-crypto/ecdsa.o
OBJS += ../vendor/detahard-crypto/hmac.o
OBJS += ../vendor/detahard-crypto/hmac_drbg.o
OBJS += ../vendor/detahard-crypto/rfc6979.o
OBJS += ../vendor/detahard-crypto/ripemd160.o
OBJS += ../vendor/detahard-crypto/secp256k1.o
OBJS += ../vendor/detahard-crypto/sha2.o
OBJS += ../vendor/detahard-crypto/bip39.o
OBJS += ../vendor/detahard-crypto/bip39_english.o
OBJS += ../vendor/detahard-crypto/pbkdf2.o
OBJS += ../vendor/detahard-crypto/memzero.o

include ../Makefile.include
